### ISSUE TITLE
Update Home Assistant 0.88.2 

### ISSUE THREAD

**Issue by Ruggyo** [sfarzo/esp_scsgate_hass#1]
Ciao,

ho seguito alla lettere la tua guida e sono riuscito a far funzionare il modulo con la versione 0.84
oggi ho eseguito l'update alla 0.88.2 e anche ripetendo tutti i passaggi dell'installazione non funziona più:
se inserisco in configuration.yaml la porta mi restituisce:
Invalid config for [scsgate]: [port] is an invalid option for [scsgate]. Check: scsgate->scsgate->port. (See /home/homeassistant/.homeassistant/configuration.yaml, line 215). Please check the docs at https://home-assistant.io/components/scsgate/

mentre se tolgo il campo:

Cannot setup SCSGate component: __init__() missing 1 required positional argument: 'port'

dove sto sbagliando?

grazie ancora per la tua guida!
Ruggiero

**Comment by BrianMay-pt** [comment]
Did you find a solution for this? I'm trying to get it to work with 0.91.1 and I cannot

cheers

**Comment by vinciop** [comment]
https://github.com/vinciop/home-assistant/blob/dev/homeassistant/components/scsgate/__init__.py
Sono riuscito a farlo funzionare con la versione 0.96.5 (l'ultima ad oggi) utilizzando il file __init__.py in allegato, da sostituire a quello che viene installato nella cartella scsgate. Questo file è stato ottenuto dal file equivalente della versione più aggiornata di home assistant, apportando le stesse modifiche che erano state apportate da Terminet85 in scsgate.py, oltre a rimuovere una sintassi nuova in Python 3.6 che genera errore in Python 3.5
